### ISSUE TITLE
fetcher.data not being parsed correctly when mocked

### ISSUE THREAD

**Issue by moishinetzer** [jrestall/remix-stubs#9]
First of all, thanks for this implementation it makes my life extremely easy mocking out my remix components.

When mocking out components that `useFetcher`, after calling `fetcher.load(route)`, the `fetcher.data` returns `"[object Object]"` as a string, and the data that is being provided to the route in the stub, with the loader being mocked out, is not sent correctly to fetchers.

Is there any solution to this?

**Comment by jrestall** [comment]
Hi @moishinetzer, thanks for the kind words! 

I'm unlikely to add support for useFetcher to remix-stubs as remix-stubs was always created as a temporary solution until the Remix team created built-in support. I'm now successfully using the nightly builds of [@remix-run/testing](https://www.npmjs.com/package/@remix-run/testing/v/0.0.0-nightly-52d60ec-20230121) with Remix v1.11.1 (using pnpm overrides to force @remix-run/node and @remix-run/react to v1.11.1 rather than nightly). I'd suggest giving that a go where you may find useFetcher works or if not you could raise an issue against Remix that will help everyone with the go-forward solution. 

Once @remix-run/testing is stable and documented I'll archive this repo and direct people to @remix-run/testing.

**Comment by moishinetzer** [comment]
Thanks for this, I really appreciate it! I'll close this for now, but I'm having some trouble figuring it out, where does the element to render inside the stub go?

**Comment by jrestall** [comment]
> Thanks for this, I really appreciate it! I'll close this for now, but I'm having some trouble figuring it out, where does the element to render inside the stub go?

The API for @remix-run/testing is very similar to remix-stubs, it's not documented yet but looking at the [tests](https://github.com/remix-run/remix/blob/dev/packages/remix-testing/__tests__/stub-test.tsx) might help. The element property on the route is what will be rendered if the route matches.
